version: "3.8"

services:
  food-recipe-be-1:
    build: .
    container_name: food-recipe-be-1
    env_file:
      - .env
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/FoodRecipe
    restart: always
    networks:
      - food-recipe-network

  food-recipe-be-2:
    build: .
    container_name: food-recipe-be-2
    env_file:
      - .env
    environment:
      - PORT=5001
      - MONGO_URI=mongodb://mongo:27017/FoodRecipe
    restart: always
    networks:
      - food-recipe-network

  # mongo:
  #   image: mongo:latest
  #   container_name: mongo
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=root
  #     - MONGO_INITDB_ROOT_PASSWORD=password123!
  #   volumes:
  #     - mongo-data:/data/db
  #   restart: always
  #   networks:
  #     - food-recipe-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - food-recipe-be-1
      - food-recipe-be-2
    restart: always
    networks:
      - food-recipe-network

networks:
  food-recipe-network:
    driver: bridge

# volumes:
#   mongo-data:
#     driver: local
